name: Feature Build

on:
    push:
        branches:
            - 'feature/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up JDK 21
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: '21'

            -   name: Build and check with Gradle
                run: ./gradlew clean build detekt
