name: Release Verification

on:
  push:
    branches:
      - 'release/**'

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Test release candidate
        run: ./gradlew clean test detekt